In [1]:
a =2 
b = 3
c =  a**b
print(c)

8


In [2]:
str = input("enter your expression")
op=""
for i in str:
    if i in "+-*/":
        op=i

str=str.replace(op," ")
l=str.split(" " )

if op=='+':
    print(float(l[0])+float(l[1]))
elif op=='-':
    print(float(l[0])-float(l[1]))                
elif op=='*':
    print(float(l[0])*float(l[1]))   
elif op=='/':
    print(float(l[0])/float([1]))
else:
     print("invalid operator")

enter your expression 5.6+6.3


11.899999999999999


In [5]:
DIP={'A':1,'B':1 ,'C':2,'D':3,'E':2,'F':2,'G':3,'H':4 ,'I':3}

DOP={}

for i in DIP.values():
    if i in DOP.keys():
        DOP[i]=DOP[i]+1
    else:
        DOP[i]=1

print(DOP)

{1: 2, 2: 3, 3: 3, 4: 1}


In [4]:
def addnum(a,b):
    c=a+b
    print(c)
    return
 
if __name__=="__main__":
    result = addnum(2,5) 
    print(result)

7
None


In [6]:
def addnum():
    a=int(input())
    b=int(input())
    c=a+b
    print(c)
    return

if __name__=="__main__":
    addnum() 

 3
 4


7


In [7]:
def pr(a):
    if(a!=2 or a!=1):
          for i in range(3,a):          
                if(a%2!=0 and a%1!=0):
                   continue
                else:
                    return 0
                return 1
    else:
        if a==2:
            return 1
        else:
            return 0
b=int(input())
r=pr(b)
if r==0:
     print("NOT PRIME")
else:
     print("PRIME")

 5


NOT PRIME


In [10]:
ab=input("enter the string")
pr=reversed(ab)
if list(ab)==list(pr):
    print("PALINDROME")
else:
    print("NOT PALINDROME") 

enter the string civic


PALINDROME


In [4]:
l=[]
for i in range(0,100,2):
    l.append(i)
    
l2=[i in range(0,100,2)]
    
print(l)
print(l2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]
[True]


In [5]:
l=[]

for i in range(0,10):
    a=input()
    l.append(a)

print(l)


 1
 2
 3
 4
 5
 6
 7
 8
 2
 3


['1', '2', '3', '4', '5', '6', '7', '8', '2', '3']


In [12]:
l=[list(map(str,input().split()))]

   
print(l)

 vansh slathia miet


[['vansh', 'slathia', 'miet']]


In [13]:
l=[tuple(map(str,input().split()))]

   
print(l)

 1 2 3 4


[('1', '2', '3', '4')]


In [18]:
class A:
    def __init__(self):
        self.a=10
        self.b=20
    def fun1(self):
        print("this is fun1 from class A")
        
class B(A):
    def __init__(self):
        self.a=11
        self.b=22
    def fun1(self):
        print("this is fun1 from class B")

if __name__=="__main__":
    obj =B()

    print(obj.a)
    print(obj.b)
    obj.fun1()

11
22
this is fun1 from class B


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr
print(arr.dtype)
arr2=np.array([1,2,3,4,5],dtype=np.int16)
arr2
#array([1,2,3,4,5],dtype=int16)

int32


array([1, 2, 3, 4, 5], dtype=int16)

In [ ]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
ar2=np.array([[1,2,3],[4,5,60]])
ar2

array([[ 1,  2,  3],
       [ 4,  5, 60]])

In [14]:
z1=np.zeros([5,5])
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
ar2.sum(axis=0)

array([ 5,  7, 63])

In [18]:
ar2

array([[ 1,  2,  3],
       [ 4,  5, 60]])

In [20]:
ar2.shape

(2, 3)

In [22]:
ar2.size

6

In [24]:
ar2.reshape([3,2])

array([[ 1,  2],
       [ 3,  4],
       [ 5, 60]])

#statistics

In [26]:
np.mean(ar2)

12.5

In [28]:
np.mean(ar2,axis=0)

array([ 2.5,  3.5, 31.5])

In [32]:
np.mean(ar2,axis=1)

array([ 2., 23.])

In [34]:
np.median(ar2)

3.5

In [36]:
np.median(ar2,axis=1)

array([2., 5.])

In [38]:
np.min(ar2)

1

In [41]:
np.min(ar2,axis=0)

array([1, 2, 3])

In [44]:
np.max(ar2,axis=0)

array([ 4,  5, 60])

In [46]:
np.argmax(ar2)

5

In [48]:
np.argmin(ar2)

0

In [50]:
np.sin(ar2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.30481062]])

2 AUG 2024



In [7]:
import numpy as np


In [9]:
ar2=np.array([[1,2,4],[1,6,9]])
ar2

array([[1, 2, 4],
       [1, 6, 9]])

In [11]:
ar3=np.array([[85,90,70],[92,88,95],[76,95,85],[90,85,92],[88,76,89]])
ar3

array([[85, 90, 70],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [73]:
a=np.mean(ar3)
a

86.4

In [57]:
np.mean(ar3,axis=1)

array([81.66666667, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [55]:
np.median(ar3,axis=0)

array([88., 88., 89.])

In [53]:
np.sum(ar3,axis=0)

array([431, 434, 431])

In [51]:
np.min(ar3,axis=1)

array([70, 88, 76, 85, 76])

In [25]:
np.max(ar3,axis=1)

array([90, 95, 95, 92, 89])

In [27]:
np.size(ar3)

15

In [35]:
np.shape(ar3)

(5, 3)

In [39]:
ar3.reshape([3,5])

array([[85, 90, 70, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [79]:
np.argmax(ar3,axis=0)

array([1, 2, 1], dtype=int64)

In [67]:
np.argmax(ar3,axis=1)

array([1, 2, 1, 2, 2], dtype=int64)

In [85]:
np.sort(ar3,axis=0)

array([[76, 76, 70],
       [85, 85, 85],
       [88, 88, 89],
       [90, 90, 92],
       [92, 95, 95]])