You are given a 2D numpy array representing exam scores of students in different subjects. The array has shape (5,3) where each row repesents a student and each column represents a subject ( math , science , english ).

scores = np.array([85,90,78] ,
                  [92,88,95] , 
                  [76,95,85] ,
                  [90,85,92] ,
                  [88,76,89] ,])

Using Numpy , perform the following tasks:
1. cal the mean score of each subject ( across all students).
2. find the median score of each student ( acrossall the students).
3. Extract the scores of the student with the highest total score ( sum of all subjects).
4. Find the minimum and maximum scores in each subjects.
5. Reshape the array to have shape (3,5) where each row represents a subject.
6. Sort the scores of each subject in ascending order.
Note : Provide the code to accomplish each task , and include comments to explain your thoughts process.

In [37]:
import numpy as np

scores = np.array([[85,90,78] ,
                  [92,88,95] ,
                  [76,95,85] ,
                  [90,85,92] ,
                  [88,76,89]] )

In [38]:
#Finding mean
np.mean(scores , axis=1)

array([84.33333333, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [39]:
#finding median score of each stident
np.median(scores,axis=1)  

array([85., 92., 85., 90., 88.])

In [40]:
#extracting the scores with highest total score
i=np.sum(scores , axis=1)
print(i)

[253 275 256 267 253]


In [41]:
index=np.argmax(i)
index

np.int64(1)

In [44]:
scores[index]

array([92, 88, 95])

In [46]:
# max & min
np.max(i)
print(i)
miin=np.min(scores,axis=1)
print(miin)

[253 275 256 267 253]
[78 88 76 85 76]


In [47]:
#reshaping the array into (3,5)
np.reshape(scores,(3,5))

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [49]:
#ascending order
np.sort(scores)

array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

In [51]:
#descending
np.sort(scores,axis=0)[:: -1]

array([[92, 95, 95],
       [90, 90, 92],
       [88, 88, 89],
       [85, 85, 85],
       [76, 76, 78]])